### ISSUE TITLE
Can't download PyQt5 with pip

### ISSUE THREAD

**Issue by karacasoft** [gurbuzbeyza/coursePlanner#2]
`pip install -r requirements` doesn't work. I think PyQt5 is a python3 package. But there're xrange's used in code. I've changed them to range, re-run the program. Had to change `urllib2` to `urllib.request`, too. After a `pip3 install -r requirements` and a `python3 coursePlanner.py`, it worked. I think the python3 requirement should be written on README.

Nice program, eyvallah!! :V

**Comment by gurbuzbeyza** [comment]
Thank you very much!
